### ISSUE TITLE
component design changes

### ISSUE THREAD

**Issue by okarem** [WebAhead/wajjbat-social#46]
Landing: 
- [x] change color scheme, in the landing(feed) page & in the profile pages
- [x] make a space between "halal-glutinfree .." and "like-favoirite-share"

addPost:
- [x] remove checkboxes down and add text field for adding tags
-   - [x] instead of "sweets glutin-free cold" put "halal kasher gluting-free"
    - [x] insted of just text put text and icons

**Comment by okarem** [comment]
any changes you think should be made to the website, please write here. if it's too long and needs a meeting in person just write a bullet point so we can discuss it in video chat

**Comment by Karyum** [comment]
![WhatsApp Image 2020-04-01 at 17 32 00](https://user-images.githubusercontent.com/24195641/78149506-c16a8780-743e-11ea-9c3b-6805dd05092a.jpeg)

the colors of the check boxes should be the site's main green (_no the copy pasted purple :laughing:_)

**Comment by shiryz** [comment]
https://en.wikipedia.org/wiki/List_of_cuisines

The client has asked to add these as tag options
I would add them to the optional tagging by the user with an autocomplete so it would be later used for searching for a recipe
We shouldn't put this in the main tagging because there are too many cuisines and not enough space

**Comment by shiryz** [comment]
For the Arabic translation, we've been asked to do the translation ourselves and they will send us any fixes later.

**Comment by shiryz** [comment]
Dietary options tags with icons:

Fusion cuisine
Haute cuisine
Note by Note cuisine
Nouvelle cuisine
Vegan cuisine
Vegetarian cuisine
Gluten free cuisine
